"""
GitHub API operations: client, issues, PRs, project board moves.
Must be called only after RunState.coverage_ok is true.
"""

import os
import json
import re
import requests
from github import Github
from github.Auth import Token


def get_github_client(token: str = None):
    """Get authenticated GitHub client"""
    if not token:
        token = os.getenv("GITHUB_TOKEN")
    if not token:
        return None
    auth = Token(token)
    return Github(auth=auth)


def get_sub_issues(repo_name: str, issue_number: int):
    """Get sub-issues (child issues) for a given parent issue"""
    g = get_github_client()
    if not g:
        return []
    
    try:
        repo = g.get_repo(repo_name)
        
        # Method 1: Try GitHub Sub-Issues API (if available)
        try:
            import requests
            token = os.getenv("GITHUB_TOKEN")
            headers = {"Authorization": f"token {token}", "Accept": "application/vnd.github+json"}
            url = f"https://api.github.com/repos/{repo_name}/issues/{issue_number}/sub-issues"
            response = requests.get(url, headers=headers, timeout=10)
            
            if response.status_code == 200:
                sub_issues_data = response.json()
                sub_issues = []
                for sub_issue_data in sub_issues_data:
                    sub_issue = repo.get_issue(sub_issue_data['number'])
                    sub_issues.append(sub_issue)
                return sub_issues
        except:
            pass
        
        # Method 2: Check issue body for linked issues (fallback)
        parent_issue = repo.get_issue(issue_number)
        if not parent_issue.body:
            return []
        
        # Pattern to find issue references: #123 or #123, #456
        issue_refs = re.findall(r'#(\d+)', parent_issue.body)
        sub_issues = []
        
        for ref_num in issue_refs:
            try:
                ref_num_int = int(ref_num)
                if ref_num_int != issue_number:
                    linked_issue = repo.get_issue(ref_num_int)
                    if linked_issue.state == 'open':
                        sub_issues.append(linked_issue)
            except:
                continue
        
        # Remove duplicates
        seen = set()
        unique_sub_issues = []
        for issue in sub_issues:
            if issue.number not in seen:
                seen.add(issue.number)
                unique_sub_issues.append(issue)
        
        return unique_sub_issues
        
    except Exception as e:
        print(f"⚠️  Warning: Could not fetch sub-issues for #{issue_number}: {e}")
        return []


def get_next_issue(repo_name: str, processed_issues_file):
    """Get the next unprocessed issue"""
    g = get_github_client()
    if not g:
        return None
    
    # Load processed issues
    processed = set()
    if processed_issues_file.exists():
        with open(processed_issues_file, 'r') as f:
            processed = set(json.load(f))
    
    # Get open issues
    repo = g.get_repo(repo_name)
    issues = repo.get_issues(state='open', sort='updated')
    
    # Find first unprocessed issue
    for issue in issues:
        if issue.number not in processed:
            return issue
    
    return None


def mark_issue_processed(issue_number: int, processed_issues_file):
    """Mark an issue as processed"""
    processed = set()
    if processed_issues_file.exists():
        with open(processed_issues_file, 'r') as f:
            processed = set(json.load(f))
    
    processed.add(issue_number)
    
    with open(processed_issues_file, 'w') as f:
        json.dump(list(processed), f)


def create_pr(repo_name: str, branch_name: str, issue_number: int, issue_title: str = None):
    """Create a pull request on GitHub"""
    try:
        g = get_github_client()
        if not g:
            print("⚠ Cannot create PR: GitHub client not available")
            return None
        
        repo = g.get_repo(repo_name)
        org_name = repo_name.split('/')[0]
        
        # Determine base branch
        base_branch = None
        for branch in ["development", "main", "master"]:
            try:
                repo.get_branch(branch)
                base_branch = branch
                break
            except:
                continue
        
        if not base_branch:
            base_branch = "main"
        
        # PR title and body
        pr_title = f"[CrewAI] Implement issue #{issue_number}"
        if issue_title:
            pr_title = f"[CrewAI] #{issue_number}: {issue_title}"
        
        pr_body = f"""Automated implementation for issue #{issue_number}.

**Generated by CrewAI agents:**
- Product Manager: Created user story and acceptance criteria
- Software Architect: Designed technical implementation plan
- Developer: Implemented code changes
- Code Reviewer: Reviewed for quality and correctness

**Issue:** #{issue_number}
**Branch:** {branch_name}

Please review the changes carefully.
"""
        
        # Check if PR already exists
        try:
            existing_prs = repo.get_pulls(head=f"{org_name}:{branch_name}", state='open')
            for pr in existing_prs:
                if pr.head.ref == branch_name:
                    print(f"✓ Pull Request already exists: {pr.html_url}")
                    return pr.html_url
        except:
            pass
        
        pr = repo.create_pull(
            title=pr_title,
            body=pr_body,
            base=base_branch,
            head=branch_name
        )
        
        print(f"✓ Created Pull Request: {pr.html_url}")
        return pr.html_url
    except Exception as e:
        error_str = str(e)
        if "422" in error_str and "already exists" in error_str.lower():
            try:
                org_name = repo_name.split('/')[0]
                existing_prs = repo.get_pulls(head=f"{org_name}:{branch_name}", state='open')
                for pr in existing_prs:
                    if pr.head.ref == branch_name:
                        print(f"✓ Pull Request already exists: {pr.html_url}")
                        return pr.html_url
            except:
                pass
        print(f"⚠ Failed to create PR: {e}")
        return None


def move_issue_in_project(repo_name: str, issue_number: int, target_column_name: str, project_name: str = None):
    """Move an issue to a specific column in GitHub project (supports both Classic and V2 Projects)"""
    try:
        g = get_github_client()
        if not g:
            print("⚠ Cannot move issue: GitHub client not available")
            return False
        
        repo = g.get_repo(repo_name)
        issue = repo.get_issue(issue_number)
        
        org_name = repo_name.split('/')[0]
        repo_name_only = repo_name.split('/')[1]
        token = os.getenv("GITHUB_TOKEN")
        
        # Try Projects V2 (GraphQL) first
        print(f"🔍 Looking for project: {project_name or 'default'}...")
        
        graphql_url = "https://api.github.com/graphql"
        headers = {
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        }
        
        query = """
        query($owner: String!, $repo: String!) {
          repository(owner: $owner, name: $repo) {
            projectsV2(first: 10) {
              nodes {
                id
                title
                number
                fields(first: 20) {
                  nodes {
                    ... on ProjectV2SingleSelectField {
                      id
                      name
                      options {
                        id
                        name
                      }
                    }
                  }
                }
              }
            }
          }
        }
        """
        
        variables = {"owner": org_name, "repo": repo_name_only}
        
        try:
            response = requests.post(graphql_url, headers=headers, json={"query": query, "variables": variables}, timeout=30)
        except (requests.exceptions.Timeout, requests.exceptions.ConnectionError) as e:
            print(f"⚠ Network error when querying GitHub Projects API: {e}")
            return False
        
        if response.status_code == 200:
            data = response.json()
            if 'errors' not in data:
                projects_v2 = data.get('data', {}).get('repository', {}).get('projectsV2', {}).get('nodes', [])
                if projects_v2:
                    project_v2 = None
                    if project_name:
                        for p in projects_v2:
                            if p.get('title') == project_name:
                                project_v2 = p
                                break
                    else:
                        project_v2 = projects_v2[0]
                    
                    if project_v2:
                        print(f"📋 Using Projects V2: {project_v2.get('title')} (ID: {project_v2.get('id')})")
                        return move_issue_in_project_v2(
                            project_v2.get('id'),
                            issue.id,
                            issue_number,
                            target_column_name,
                            project_v2.get('fields', {}).get('nodes', []),
                            token
                        )
        
        # Fallback to classic projects (REST API)
        print("   Trying classic projects (REST API)...")
        project = None
        projects = []
        
        try:
            projects = list(repo.get_projects())
            print(f"📋 Found {len(projects)} repository-level classic project(s)")
        except:
            projects = []
        
        if not projects:
            try:
                user = g.get_user(org_name)
                projects = list(user.get_projects())
                print(f"📋 Found {len(projects)} user-level classic project(s)")
            except:
                projects = []
        
        if not projects:
            print("⚠ No projects found")
            return False
        
        if project_name:
            for p in projects:
                if p.name == project_name:
                    project = p
                    break
        else:
            project = projects[0]
        
        if not project:
            print(f"⚠ Project '{project_name or 'default'}' not found")
            return False
        
        print(f"📋 Using classic project: {project.name} (ID: {project.id})")
        
        columns = list(project.get_columns())
        print(f"📋 Found {len(columns)} columns: {[c.name for c in columns]}")
        
        target_column = None
        issue_card = None
        source_column = None
        
        for column in columns:
            if column.name == target_column_name:
                target_column = column
                break
        
        for column in columns:
            if issue_card:
                break
            try:
                cards = list(column.get_cards())
                for card in cards:
                    try:
                        content = card.get_content()
                        if hasattr(content, 'number') and content.number == issue_number:
                            issue_card = card
                            source_column = column
                            print(f"   ✓ Found issue #{issue_number} in column '{column.name}'")
                            break
                    except:
                        continue
            except Exception as e:
                continue
        
        if not target_column:
            print(f"⚠ Target column '{target_column_name}' not found")
            return False
        
        if not issue_card:
            print(f"⚠ Issue #{issue_number} not found in project. Adding to '{target_column_name}'...")
            try:
                url = f"https://api.github.com/projects/columns/{target_column.id}/cards"
                headers = {
                    "Authorization": f"Bearer {token}",
                    "Accept": "application/vnd.github+json",
                    "X-GitHub-Api-Version": "2022-11-28"
                }
                data = {"content_id": issue.id, "content_type": "Issue"}
                response = requests.post(url, headers=headers, json=data)
                if response.status_code in [201, 200]:
                    print(f"✓ Added issue #{issue_number} to '{target_column_name}'")
                    return True
            except Exception as e:
                print(f"⚠ Failed to add issue to project: {e}")
                return False
        
        if source_column and source_column.id == target_column.id:
            print(f"✓ Issue #{issue_number} already in '{target_column_name}'")
            return True
        
        url = f"https://api.github.com/projects/columns/cards/{issue_card.id}/moves"
        headers = {
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28"
        }
        data = {"position": "top", "column_id": target_column.id}
        
        print(f"🔄 Moving issue #{issue_number} from '{source_column.name if source_column else 'unknown'}' to '{target_column_name}'...")
        response = requests.post(url, headers=headers, json=data)
        
        if response.status_code in [201, 200]:
            print(f"✓ Moved issue #{issue_number} to '{target_column_name}'")
            return True
        else:
            print(f"⚠ Failed to move card: {response.status_code}")
            return False
            
    except Exception as e:
        print(f"⚠ Error moving issue in project: {e}")
        return False


def move_issue_in_project_v2(project_id: str, issue_id: int, issue_number: int, 
                             target_field_value: str, fields: list, token: str):
    """Move an issue in a Projects V2 using GraphQL"""
    try:
        graphql_url = "https://api.github.com/graphql"
        headers = {
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        }
        
        status_field = None
        target_option_id = None
        status_field_names = ['status', 'state', 'stage', 'progress', 'column']
        
        for field in fields:
            field_name_lower = field.get('name', '').lower()
            if any(name in field_name_lower for name in status_field_names):
                status_field = field
                options = field.get('options', [])
                for opt in options:
                    if opt.get('name', '').lower() == target_field_value.lower():
                        target_option_id = opt.get('id')
                        break
                if not target_option_id:
                    for opt in options:
                        opt_name = opt.get('name', '').lower()
                        if target_field_value.lower() in opt_name or opt_name in target_field_value.lower():
                            target_option_id = opt.get('id')
                            break
                break
        
        if not status_field or not target_option_id:
            print(f"⚠ Status field or target option not found")
            return False
        
        # Get project item
        query_item = """
        query($projectId: ID!) {
          node(id: $projectId) {
            ... on ProjectV2 {
              items(first: 100) {
                nodes {
                  id
                  content {
                    ... on Issue {
                      id
                      number
                    }
                  }
                }
              }
            }
          }
        }
        """
        
        try:
            response = requests.post(graphql_url, headers=headers, 
                                   json={"query": query_item, "variables": {"projectId": project_id}}, timeout=30)
        except (requests.exceptions.Timeout, requests.exceptions.ConnectionError) as e:
            print(f"⚠ Network error: {e}")
            return False
        
        if response.status_code != 200:
            return False
        
        data = response.json()
        if 'errors' in data:
            return False
        
        items = data.get('data', {}).get('node', {}).get('items', {}).get('nodes', [])
        project_item_id = None
        
        for item in items:
            if item.get('content', {}).get('number') == issue_number:
                project_item_id = item.get('id')
                break
        
        if not project_item_id:
            # Add issue to project first
            content_id = issue_id
            if not str(issue_id).startswith('Issue_'):
                content_id = f"Issue_{issue_id}"
            
            mutation_add = """
            mutation($projectId: ID!, $contentId: ID!) {
              addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                item { id }
              }
            }
            """
            
            try:
                response_add = requests.post(graphql_url, headers=headers,
                                            json={"query": mutation_add, 
                                                  "variables": {"projectId": project_id, "contentId": content_id}}, 
                                            timeout=30)
                if response_add.status_code == 200:
                    data_add = response_add.json()
                    if 'errors' not in data_add:
                        project_item_id = data_add.get('data', {}).get('addProjectV2ItemById', {}).get('item', {}).get('id')
                        if project_item_id:
                            print(f"✓ Added issue #{issue_number} to project")
            except:
                return False
        
        # Update status
        mutation_update = """
        mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) {
          updateProjectV2ItemFieldValue(input: {
            projectId: $projectId
            itemId: $itemId
            fieldId: $fieldId
            value: {singleSelectOptionId: $optionId}
          }) {
            projectV2Item { id }
          }
        }
        """
        
        variables_update = {
            "projectId": project_id,
            "itemId": project_item_id,
            "fieldId": status_field.get('id'),
            "optionId": target_option_id
        }
        
        try:
            response_update = requests.post(graphql_url, headers=headers,
                                          json={"query": mutation_update, "variables": variables_update}, timeout=30)
            if response_update.status_code == 200:
                data_update = response_update.json()
                if 'errors' not in data_update:
                    print(f"✓ Moved issue #{issue_number} to '{target_field_value}'")
                    return True
        except:
            pass
        
        return False
            
    except Exception as e:
        print(f"⚠ Error in Projects V2 movement: {e}")
        return False
